### ISSUE TITLE
Bij niveaus worden vakken weergegeven die daar niet logisch bij horen

### ISSUE THREAD

**Issue by allardstrijkerslo** [slonl/curriculum-basis#4]
https://opendata.slo.nl/curriculum/api-acpt/v1/uuid/512e4729-03a4-43a2-95ba-758071d1b725/ toont niveaus bij vakken die verwarrend werken. 

Oplossing, toon bij niveaus geen vakken.

**Comment by poef** [comment]
Is voor zover ik kan zien nu geen probleem meer.
