### ISSUE TITLE
Volgorde van items is niet alfabetisch

### ISSUE THREAD

**Issue by allardstrijkerslo** [slonl/curriculum-basis#5]

**Comment by poef** [comment]
De doelniveau's hebben zelf geen titel om op te sorteren, de titel die je ziet is van onderliggende doel (of kerndoel of examenprogrammaeindterm). Daarnaast levert de hoeveelheid items technisch een probleem op - als je dit sorteert duurt het erg lang voordat je response krijgt. Omdat deze lijst zo groot is, is de lijst eigenlijk niet zinvol om zo te gebruiken, dus deze lijst sorteren is niet renderend.
